{% set name = "jhsingle-native-proxy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('_', '-') }}/{{ name }}-{{ version }}.tar.gz
  sha256: c995a7f094ca6a7fa1f92a858731ad8545938a08bbdb1aabf14ef8db185401cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - jhsingle-native-proxy = jhsingle_native_proxy.main:run

requirements:
  host:
    - pip
    - python >=3.6.0,<4.0.0
  run:
    - python >=3.6.0,<4.0.0
    - jupyterhub >=1.0.0
    - tornado >=6.0.4
    - click >=7.0
    - aiohttp
    - simpervisor >=0.4

test:
  imports:
    - jhsingle_native_proxy
  requires:
    - pip
  commands:
    - pip check
    - jhsingle-native-proxy --help

about:
  home: https://github.com/ideonate/jhsingle-native-proxy
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - LICENSE-jupyter-server-proxy
  summary: Wrap an arbitrary webapp so it can be used in place of jupyter-singleuser in a JupyterHub setting

extra:
  recipe-maintainers:
    - danlester
    - fcollonval
