{% set name = "jhsingle-native-proxy" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace('_', '-') }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb47a905a8b5c64f9d95f0690210d782620ed5ca764cff1c45b96344810069b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - jhsingle-native-proxy = jhsingle_native_proxy.main:run

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0
    - jupyterhub >=1.0.0
    - tornado >=6.0.4
    - click >=7.0
    - aiohttp
    - simpervisor >=0.4,<1.0.0

test:
  imports:
    - jhsingle_native_proxy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - jhsingle-native-proxy --help

about:
  home: https://github.com/ideonate/jhsingle-native-proxy
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - LICENSE-jupyter-server-proxy
  summary: Wrap an arbitrary webapp so it can be used in place of jupyter-singleuser in a JupyterHub setting

extra:
  recipe-maintainers:
    - danlester
    - fcollonval
